// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQxgUKKAQEQhf6CqlZDkZBarwfi2kIgdc',
    appId: '1:156251911206:web:4a04b648c3050c33bbe2e7',
    messagingSenderId: '156251911206',
    projectId: 'codewizquiz',
    authDomain: 'codewizquiz.firebaseapp.com',
    storageBucket: 'codewizquiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaBuWrrLzPvp1LpY1Rlvd_wCd-pDtz0TA',
    appId: '1:156251911206:android:f91622f50c5cab05bbe2e7',
    messagingSenderId: '156251911206',
    projectId: 'codewizquiz',
    storageBucket: 'codewizquiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZmTOBPf5GM1Y4Zu6kqc16WJXTOh3pnEY',
    appId: '1:156251911206:ios:8069bd1fc83039dfbbe2e7',
    messagingSenderId: '156251911206',
    projectId: 'codewizquiz',
    storageBucket: 'codewizquiz.appspot.com',
    iosClientId: '156251911206-m2jum3fks3adm0hpm2pqu2nb4o6fi0fc.apps.googleusercontent.com',
    iosBundleId: 'com.geekaid.codewizQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZmTOBPf5GM1Y4Zu6kqc16WJXTOh3pnEY',
    appId: '1:156251911206:ios:8069bd1fc83039dfbbe2e7',
    messagingSenderId: '156251911206',
    projectId: 'codewizquiz',
    storageBucket: 'codewizquiz.appspot.com',
    iosClientId: '156251911206-m2jum3fks3adm0hpm2pqu2nb4o6fi0fc.apps.googleusercontent.com',
    iosBundleId: 'com.geekaid.codewizQuiz',
  );
}
